### ISSUE TITLE
How do we stop people spamming with nonsense args

### ISSUE THREAD

**Issue by ijmccallum** [WikiLogic/Server#107]
specifically - if there's a claim you don't like, what's to stop you putting together an argument with any random reasons that happen to be 'true' which would then set the claim you don't like to 'false'.

**Comment by DouglasUT2018** [comment]
This is dealt with the same way Wikipedia deal with it - imperfectly but somehow works out in the end! ;) Some examples of what Wikipedia do is banning IPs, locking down certain issues that have become hot beds for 'edit wars' using backed up histories to quickly restore anything targeted by vandalism etc.

**Comment by ijmccallum** [comment]
Might want to keep this one open until one of us / someone else has implemented it!

**Comment by DouglasUT2018** [comment]
Ah, thought the task was just a about the idea. I would say that this should be one of the very last things we develop and it wont make it into any prototype stage as we dont need to test the concept(its just a versioning system)

**Comment by ijmccallum** [comment]
old repo - clearing issues
