### ISSUE TITLE
Publishing drafts takes from the bottom of the list

### ISSUE THREAD

**Issue by DouglasUT2018** [WikiLogic/Server#155]
Reproduce - Create 2+ drafts. Click the publish button at the item on the top of the list. The item will be created in published but it will also stay in drafts. Instead the bottom item in drafts will be deleted. 

Current work around - publish items at the bottom first!

Notes: Maybe we can have another lesson where you fix this in front of me?

**Comment by ijmccallum** [comment]
Didn't see this issue :( It did get fixed though! Buuuuut now drafts are no more
