### ISSUE TITLE
Draft claim not appearing

### ISSUE THREAD

**Issue by DouglasUT2018** [WikiLogic/Server#156]
Tried adding again but didnt add. It was in db not showing. Believe it doesn't add again because it checks for duplicates? If not duplicate check then maybe hints towards issue...
This can be closed or archived if to vague

**Comment by ijmccallum** [comment]
Drafts are no more! May become an issue again with claims - but also new architecture should help to deal with this. Error messages are getting passed back now (though not yet tested with duplicate claims)
