### ISSUE TITLE
Hook into voice API for real time fact checking

### ISSUE THREAD

**Issue by ijmccallum** [WikiLogic/Server#185]
EG: Amazon Echo - imagine setting it to monitor a debate and check all statements live, the top ring might indicate t/f as the speaker is making points.

**Comment by DouglasUT2018** [comment]
Do you get replies here?

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=5.1.1&source=email_footer_2] On Wed, Apr 20, 2016 at 1:36 pm, Iain J McCallum < notifications@github.com [notifications@github.com] > wrote:
EG: Amazon Echo - imagine setting it to monitor a debate and check all statements live, the top ring might indicate t/f as the speaker is making points.

**Comment by ijmccallum** [comment]
old repo - clearing issues
